name: Test Playwright (Docker Build)

on:
  push:
    branches:
      - playwright-ci-test

jobs:
  build-and-test:
    uses: ./.github/workflows/playwright-test-reusable.yml
    with:
      test-mode: docker-build
    secrets: inherit
