name: Test Playwright (Docker Pull)

on:
  workflow_dispatch:
    inputs:
      containers:
        description: 'Shard containers to use'
        required: false
        default: '[1, 2]'
        type: string
      image:
        description: 'Image to use'
        required: false
        default: 'n8nio/n8n:nightly'
        type: string
  push:
    branches:
      - playwright-ci-test

env:
  TESTCONTAINERS_RYUK_DISABLED: true
  PLAYWRIGHT_BROWSERS_PATH: packages/testing/playwright/ms-playwright-cache
  N8N_DOCKER_IMAGE: 'n8nio/n8n:nightly'

jobs:
  build-and-test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup and Install
        uses: ./.github/actions/setup-blacksmith
        with:
          build-command: pnpm turbo install-browsers:ci
          enable-docker-cache: true

      - name: Run Playwright tests
        env:
          N8N_DOCKER_IMAGE: ${{ inputs.image || env.N8N_DOCKER_IMAGE }}
        run: pnpm --filter=n8n-playwright run test:standard --workers=2

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            packages/testing/playwright/playwright-report/
            packages/testing/playwright/test-results/
          retention-days: 3
