name: Playwright Test
on:
  workflow_call:
    inputs:
      shards:
        description: 'Shards for parallel execution'
        required: false
        default: '[1]'
        type: string

jobs:
  testing:
    uses: ./.github/workflows/playwright-test-reusable.yml
    with:
      test-mode: local
      shards: ${{ inputs.shards || '[1]' }}
    secrets: inherit
