name: Playwright Tests

on:
  push:
    branches: [playwright-test]
  workflow_dispatch:
    inputs:
      containers:
        description: 'Shard containers to use'
        required: false
        default: '[1, 2]'
        type: string

jobs:
  testing:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    container:
      image: mcr.microsoft.com/playwright:v1.53.1-jammy
      options: --privileged
      env:
        VM_ID: ${{ env.VM_ID }}
        GITHUB_REPO_NAME: ${{ env.GITHUB_REPO_NAME }}
        BLACKSMITH_STICKYDISK_TOKEN: ${{ env.BLACKSMITH_STICKYDISK_TOKEN }}
        BLACKSMITH_INSTALLATION_MODEL_ID: ${{ env.BLACKSMITH_INSTALLATION_MODEL_ID }}
        BLACKSMITH_REGION: ${{ env.BLACKSMITH_REGION }}
    strategy:
      fail-fast: false
      matrix:
        containers: ${{ fromJSON(inputs.containers || '[1, 2]') }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.0.0

      - name: Setup Node.js
        uses: useblacksmith/setup-node@65c6ca86fdeb0ab3d85e78f57e4f6a7e4780b391 # v5.0.4
        with:
          node-version: 22.x

      - name: Mount pnpm store sticky disk
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-pnpm-store-v3
          path: ~/.local/share/pnpm/store

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Start local server
        run: |
          E2E_TESTS=true pnpm start &
          npx wait-on http://localhost:5678 --timeout 20000

      - name: Run Playwright tests (shard ${{ matrix.containers }}/${{ strategy.job-total }})
        working-directory: playwright
        run: pnpm exec playwright test --shard=${{ matrix.containers }}/${{ strategy.job-total }} --workers=4
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: results-${{ matrix.containers }}.xml
          CI: true
          TEST_SHARD_INDEX: ${{ matrix.containers }}
          N8N_BASE_URL: http://localhost:5678
          RESET_E2E_DB: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-results-${{ matrix.containers }}
          path: |
            playwright/blob-report/
            playwright/test-results/
            playwright/results-${{ matrix.containers }}.xml
          retention-days: 7

  merge-reports:
    if: always()
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x

      - name: Install dependencies
        working-directory: playwright
        run: pnpm install --frozen-lockfile

      - name: Download all test results
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: playwright-results-*
          path: all-reports/

      - name: Merge test reports
        working-directory: playwright
        run: |
          pnpm exec playwright merge-reports \
            --reporter=html,github \
            ../all-reports/playwright-results-*/blob-report

      - name: Upload merged report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report-merged
          path: playwright/playwright-report/
          retention-days: 14

  check_testing_matrix:
    runs-on: ubuntu-latest
    needs: [testing]
    outputs:
      all_tests_passed: ${{ steps.all_tests_passed.outputs.result }}
    steps:
      - name: Check all tests passed
        id: all_tests_passed
        run: |
          if [ "${{ needs.testing.result }}" == "success" ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi
